# fly.toml app configuration file generated for lmsysmd-web on 2024-06-20T21:19:11-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lmsysmd-web'
primary_region = 'yyz'

[build]
  image = 'registry.fly.io/lmsysmd-web:latest'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
